CREATE TABLE DEPT(
DEPTNO INT NOT NULL,
DNAME VARCHAR(50),
LOC VARCHAR(50),
constraint DEPTNO_PK PRIMARY KEY (DEPTNO)
);

INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES(10,'ACCOUNTING','NEW YORK');

INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES(20,'RESEARCH','DALLAS');

INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES(30,'SALES','CHICAGO');

INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES(40,'OPERATIONS','BOSTON');
 
COMMIT;
